language: php
git:
  depth: 5

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: TYPO3_VERSION=10.4.*
    - php: 7.3
      env: TYPO3_VERSION=10.4.*
    - php: 7.4
      env: TYPO3_VERSION=10.4.*

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache


before_install:
    - phpenv config-rm xdebug.ini || echo "xdebug not available"

install:
  - bash pipeline.sh

script:
   - ./vendor/bin/grumphp run
   - composer test
